workflows:

  ios-workflow:

    name: iOS Workflow

    

    # ....

    

    environment:

      ios_signing:

        provisioning_profiles:

          - Mehdi3

          # - ...

        certificates:

          - HamidReza2

          # - ...
