workflows:
  ios-distribute:
    name: iOS Build and Distribute
    environment:
      vars:
        XCODE_PROJECT: "arkitevideo.xcodeproj"
        XCODE_SCHEME: "arkitevideo"
      xcode: latest
    scripts:
      - name: Set build number from Git
        script: |
          cd $CM_BUILD_DIR
          agvtool new-version -all $(($(git rev-list --count HEAD) + 1))

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
