workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "arkitevideo.xcworkspace"  # Replace with your workspace name
        XCODE_SCHEME: "arkitevideo"               # Replace with your scheme name
        APP_STORE_APPLE_ID: "QMCS3QNWSP"      # Replace with your App Store Apple ID from App Store Connect
      xcode: latest
    integrations:
      app_store_connect: codemagic  # Reference name of your App Store Connect API key
    scripts:
      - name: Install Dependencies
        script: |
          pod install
      - name: Increment Build Number
        script: |
          #!/bin/sh
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build IPA for Distribution
        script: |
          xcode-project build-ipa \
            --workspace "ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options '{"testFlightInternalTestingOnly": true}'  # For internal testing
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true  # Submit to TestFlight beta review
        beta_groups:               # Optional: Add beta groups for external testers
          - "Beta Testers Group"
