workflows:
  ios-workflow:
    name: Custom Workflow
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - admin
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hamid.arkit.new
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles \
            --project "/Users/builder/clone/arkitevideo.xcodeproj"

      - name: Verify schemes & dump Build Settings
        script: |
          cd /Users/builder/clone
          xcodebuild -list \
            -project arkitevideo.xcodeproj
          xcodebuild \
            -project arkitevideo.xcodeproj \
            -scheme arkitevideo \
            -sdk iphoneos \
            -showBuildSettings

      - name: Build App (.ipa)
        script: |
          cd /Users/builder/clone
          xcodebuild clean archive \
          -project arkitevideo.xcodeproj \
          -scheme arkitevideo \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/arkitevideo.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
         


    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true 
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group name 1
          - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
        
