workflows:
  ios-workflow:
    name: iOS Build for TestFlight
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Mehdi  # API key integration name
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hamid.arkit.new
    scripts:
      - name: Setup Code Signing
        script: |
          xcode-project use-profiles  # Generates/fetches provisioning profiles
          xcode-project set-code-sign-style \
            --project "ios/arkitevideo.xcodeproj" \
            --code_sign_style "Automatic"

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "ios/arkitevideo.xcodeproj" \
            --scheme "arkitevideo" \
            --archive-xcargs "-allowProvisioningUpdates"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration  # <-- Authentication goes here instead
        submit_to_testflight: true
