workflows:
  ios-workflow:
    name: Manual Archive Workflow
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - admin
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hamid.arkit.new
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles \
            --project "arkitevideo.xcodeproj"

      - name: Archive App for iOS
        script: |
          ARCHIVE_PATH="/Users/builder/clone/build/ios/xcarchive/arkitevideo.xcarchive"
          xcodebuild archive \
            -project "arkitevideo.xcodeproj" \
            -scheme "arkitevideo" \
            -sdk iphoneos \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            DEVELOPMENT_TEAM=QMCS3QNWSP \
            COMPILER_INDEX_STORE_ENABLE=NO \
            | tee /tmp/xcodebuild_logs/archive.log

      - name: Export IPA from Archive
        script: |
          EXPORT_OPTIONS_PLIST="/Users/builder/exportOptions.plist"
          cat <<EOF > $EXPORT_OPTIONS_PLIST
          {
            "method": "app-store",
            "teamID": "QMCS3QNWSP",
            "signingStyle": "manual",
            "stripSwiftSymbols": true,
            "compileBitcode": true,
            "destination": "export",
            "manageAppVersionAndBuildNumber": false
          }
          EOF

          xcodebuild -exportArchive \
            -archivePath "/Users/builder/clone/build/ios/xcarchive/arkitevideo.xcarchive" \
            -exportPath "/Users/builder/clone/build/ios/ipa" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            | tee /tmp/xcodebuild_logs/export.log

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
