workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.ashen.testapp"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
    scripts:
      - name: Build ipa
        script: xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -sdk iphoneos -configuration Release archive -archivePath $HOME/build/MyApp.xcarchive
      - name: Export ipa
        script: xcodebuild -exportArchive -archivePath $HOME/build/MyApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $HOME/build/ipa
    artifacts:
      - build/ipa/*.ipa
    publishing:
      app_store_connect:
        bundle_id: $BUNDLE_ID
        api_key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
