workflows:
  ios-testflight:
    name: iOS Build & Upload to TestFlight
    max_build_duration: 60
    environment:
      vars:
        APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_P8: ${{ secrets.APP_STORE_CONNECT_API_KEY_P8 }}
      xcode: latest
      cocoapods: default
      ruby: default
    scripts:
      - name: Install dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi
      - name: Build and archive app
        script: |
          xcodebuild clean archive \
            -project arkitevideo.xcodeproj \
            -scheme arkitevideo \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/arkitevideo.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/arkitevideo.xcarchive \
            -exportPath $CM_BUILD_DIR/build/export \
            -exportOptionsPlist ExportOptions.plist
      - name: Upload to TestFlight
        script: |
          echo "$APP_STORE_CONNECT_API_KEY_P8" > AuthKey.p8
          gem install fastlane
          fastlane pilot upload \
            --ipa $CM_BUILD_DIR/build/export/*.ipa \
            --api_key_path ./AuthKey.p8 \
            --api_key_id "$APP_STORE_CONNECT_KEY_ID" \
            --issuer_id "$APP_STORE_CONNECT_ISSUER_ID"
