workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "arkitevideo.xcodeproj"
        XCODE_SCHEME:    "arkitevideo"
        APP_STORE_APPLE_ID: "QMCS3QNWSP"
    xcode: latest
    integrations:
      app_store_connect: codemagic
    scripts:
      - name: Increment Build Number
        script: |
          cd $CM_BUILD_DIR
          LATEST=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $((LATEST + 1))
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
   
