workflows:
  ios-workflow:
    name: iOS Build for TestFlight
    integrations:
      app_store_connect: Mehdi  # اسمی که توی Codemagic برای API Key گذاشتی
    environment:
      ios_signing:
        distribution_type: app_store  # برای TestFlight باید app_store باشه
        bundle_identifier: com.hamid.arkit.new
    scripts:
      - name: تنظیم امضای خودکار
        script: |
          xcode-project set-code-sign-style \
            --project "ios/arkitevideo.xcodeproj" \  # اسم پروژه‌ات رو بذار (مثلاً ios/MyApp.xcodeproj)
            --style "Automatic"
      - name: ساخت IPA
        script: |
          xcode-project build-ipa \
            --project "ios/arkitevideo.xcodeproj" \  # اسم پروژه‌ات
            --scheme "arkitevideo" \  # اسم scheme پروژه‌ات (توی Xcode قابل دیدنه)
            --archive-xcargs "-allowProvisioningUpdates"
    artifacts:
      - build/ios/ipa/*.ipa
   
