workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "arkitevideo.xcodeproj"  # Ensure this is correct (use .xcworkspace if applicable)
        XCODE_SCHEME: "arkitevideo"               # Verify this matches your Xcode scheme
        APP_STORE_APPLE_ID: "QMCS3QNWSP"         # Your App Store Apple ID
      xcode: latest
    integrations:
      app_store_connect: codemagic              # Codemagic-managed App Store Connect integration
    scripts:
      - name: Increment Build Number
        script: |
          #!/bin/sh
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Create Export Options Plist
        script: |
          echo "Creating export_options.plist"
          cat <<EOF > export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
           <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>QMCS3QNWSP</string>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <true/>
           </dict>
          </plist>
          EOF
      - name: Build IPA for Distribution
        script: |
          xcodebuild \
           -project arkitevideo.xcodeproj \
           -scheme arkitevideo \
           -archivePath /Users/builder/clone/build/ios/xcarchive/arkitevideo.xcarchive \
           archive \
           COMPILER_INDEX_STORE_ENABLE=NO \
           DEVELOPMENT_TEAM=QMCS3QNWSP \
           CODE_SIGN_STYLE=Auto 
           
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
