workflows:
  ios-workflow:
    name: Custom Workflow
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - admin
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hamid.arkit.new
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles \
            --project "/Users/builder/clone/arkitevideo.xcodeproj"

      - name: Verify schemes & dump Build Settings
        script: |
          cd /Users/builder/clone
          xcodebuild -list \
            -project arkitevideo.xcodeproj
          xcodebuild \
            -project arkitevideo.xcodeproj \
            -scheme arkitevideo \
            -sdk iphoneos \
            -showBuildSettings

      - name: Build App (.ipa)
        script: |
          cd /Users/builder/clone
          xcodebuild clean archive \
          -project arkitevideo.xcodeproj \
          -scheme arkitevideo \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/arkitevideo.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

          xcodebuild -exportArchive \
          -archivePath build/arkitevideo.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true 
        expire_build_submitted_for_review: true
        
