name: iOS Build & Upload to TestFlight

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Install dependencies
        run: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          fi

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Build app
        run: |
          xcodebuild \
            -workspace YourApp.xcworkspace \ # یا .xcodeproj
            -scheme YourApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/YourApp.xcarchive \
            clean archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/YourApp.xcarchive \
            -exportPath $PWD/build/export \
            -exportOptionsPlist ExportOptions.plist

      - name: Create Fastlane API key file
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY_P8 }}" > ./AuthKey.p8

      - name: Upload to TestFlight using Fastlane
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          fastlane pilot upload \
            --ipa build/export/*.ipa \
            --api_key_path ./AuthKey.p8 \
            --api_key_id "$APP_STORE_CONNECT_KEY_ID" \
            --issuer_id "$APP_STORE_CONNECT_ISSUER_ID"
